### PR TITLE
Integration with Dates

### LINKED ISSUE #17: Integrate Dates to compute time to maturity
Allow the interface to support `Base.Dates`. This would allow defining valuation and expiration date.

### LINKED ISSUE #35: Fix CompatHelper job
Issue:

```
┌ Error: The dependency was not found in any of the registries
│   dep.package.name = "Random"
│   dep = CompatHelper.DepInfo(CompatHelper.Package("Random", Base.UUID("9a3f8284-a2c9-5f02-9a11-845980a1fd5c")), nothing, VersionSpec("1.1.0 - 1"), "1.1")
└ @ CompatHelper ~/.julia/packages/CompatHelper/K9Pyo/src/utilities/new_versions.jl:198
┌ Info: latest_version in version_spec
│   dep.latest_version = v"0.25.113"
│   dep.version_spec = VersionSpec("0.25")
│   dep.package.name = "Distributions"
└   dep = CompatHelper.DepInfo(CompatHelper.Package("Distributions", Base.UUID("31c24e10-a181-5473-b8eb-7969acd0382f")), v"0.25.113", VersionSpec("0.25"), "0.25")
┌ Error: The dependency was not found in any of the registries
│   dep.package.name = "Test"
│   dep = CompatHelper.DepInfo(CompatHelper.Package("Test", Base.UUID("8dfed614-e22c-5e08-85e1-65c5234f0b40")), nothing, VersionSpec("1.1.0 - 1"), "1.1")
└ @ CompatHelper ~/.julia/packages/CompatHelper/K9Pyo/src/utilities/new_versions.jl:198
┌ Error: The dependency was not found in any of the registries
│   dep.package.name = "Dates"
│   dep = CompatHelper.DepInfo(CompatHelper.Package("Dates", Base.UUID("ade2ca70-3891-5945-98fb-dc099432e06a")), nothing, VersionSpec("1.1.0 - 1"), "1.1")
└ @ CompatHelper ~/.julia/packages/CompatHelper/K9Pyo/src/utilities/new_versions.jl:198
```

### PR DESCRIPTION
**Pull request by mvanzulli**
Closes #17 
Closes #35

### CODE REVIEW

File: src/derivatives.jl [hunk 1]
```diff
@@ -34,6 +34,14 @@ Abstract type for [swaption](https://en.wikipedia.org/wiki/Swaption).
 """
 abstract type Swaption <: Derivative end
 
+"Compute the time to expiration in years between two dates."
+function time_to_expiration(t0::Date, t1::Date)
+    t1 > t0 || throw(ArgumentError("Expiry date $t1 must be greater issue date $t0"))
```
Comment (iblislin) [inline src/derivatives.jl]:
```suggestion
    t1 > t0 || throw(ArgumentError("Expiry date $t1 must be greater than issue date $t0"))
```

**Review by iblislin — APPROVED** [review]
